package dev.rudami.claudeacp

import com.intellij.openapi.util.SystemInfo
import java.nio.file.Path
import kotlin.io.path.createParentDirectories
import kotlin.io.path.writeText

/**
 * Writes the small script `acp.json` points at.
 *
 * A launcher exists for one reason: `env` in `acp.json` can only *set* variables, never
 * remove them, and Claude Code bills through the API instead of the subscription whenever
 * `ANTHROPIC_API_KEY` (or an auth token, or a Bedrock/Vertex switch) is present in the
 * environment it inherits from the IDE. Unsetting them has to happen in a process between
 * the IDE and the adapter.
 *
 * It is regenerated whenever the version or the node binary changes rather than patched.
 */
object LauncherScript {

    /**
     * Prefix of the marker a launcher leaves in its version directory, named by the pid it
     * ends up running as. Read by `AdapterInstaller.versionsInUse`.
     */
    const val MARKER_PREFIX: String = ".in-use."

    private val CLEARED_VARIABLES = listOf(
        "ANTHROPIC_API_KEY",
        "ANTHROPIC_AUTH_TOKEN",
        "ANTHROPIC_API_KEY_HELPER",
        "CLAUDE_CODE_USE_BEDROCK",
        "CLAUDE_CODE_USE_VERTEX",
    )

    fun path(root: Path): Path = root.resolve(if (SystemInfo.isWindows) "launch.cmd" else "launch.sh")

    /**
     * Writes the launcher for [entryPoint] and returns its path.
     *
     * Written atomically: the IDE starts a chat by running this script, and rewriting it in
     * place — which provisioning does on every startup and every version change — leaves a
     * window where a starting agent reads a truncated file.
     */
    fun write(root: Path, runtime: NodeRuntime, entryPoint: Path, versionDirectory: Path): Path {
        val script = path(root)
        val body = if (SystemInfo.isWindows) {
            windows(runtime, entryPoint)
        } else {
            posix(runtime, entryPoint, versionDirectory)
        }

        script.writeAtomically(body, executable = !SystemInfo.isWindows)
        return script
    }

    private fun posix(runtime: NodeRuntime, entryPoint: Path, versionDirectory: Path): String = buildString {
        appendLine("#!/bin/sh")
        appendLine("# Generated by the Claude Code ACP Bridge plugin. Edits are overwritten.")
        appendLine("#")
        appendLine("# Note what is absent from the exec line: --hide-claude-auth. That flag is what")
        appendLine("# the IDE's own Claude agent passes, and it both hides the subscription login and")
        appendLine("# rejects subscription credentials at session start.")
        appendLine()
        CLEARED_VARIABLES.forEach { appendLine("unset $it") }
        appendLine()
        appendLine("PATH=\"${runtime.binDir}:\$PATH\"")
        appendLine("export PATH")
        appendLine()
        appendLine("# Marks this version as in use, so cleanup does not delete the adapter out")
        appendLine("# from under a running chat. No trap cleans it up because exec replaces this")
        appendLine("# shell — which is also what makes the name reliable: exec keeps the pid, so")
        appendLine("# the file names the node process, and a stale marker is one whose pid is")
        appendLine("# gone. Best effort; the plugin also spares versions it sees running.")
        appendLine(": > \"$versionDirectory/$MARKER_PREFIX\$\$\" 2>/dev/null || true")
        appendLine()
        appendLine("exec \"${runtime.node}\" \"$entryPoint\" \"\$@\"")
    }

    private fun windows(runtime: NodeRuntime, entryPoint: Path): String = buildString {
        appendLine("@echo off")
        appendLine("rem Generated by the Claude Code ACP Bridge plugin. Edits are overwritten.")
        CLEARED_VARIABLES.forEach { appendLine("set \"$it=\"") }
        appendLine("set \"PATH=${runtime.binDir};%PATH%\"")
        appendLine("\"${runtime.node}\" \"$entryPoint\" %*")
    }
}
